### PR TITLE
Various features

### PR DESCRIPTION
**Pull request by Vinjul1704**
This PR adds a few features. Yes, this is too much at once and very much the "minor fixes, +1231464343 changes" meme, but here we go:
- Add text labels, in order to organize the debug menu a bit more. Relies on this practice-tool-core PR: https://github.com/veeenu/practice-tool-core/pull/15
- Restructure the way indicators are handled a bit and add an ingame-menu to toggle the individual ones without having to restart the game. This also comes with a small change in how the overlay is displayed, since the buttons are now underneath the text and there's an additional line break between those buttons and the indicators. Please let me know if it should be tweaked some more, however I think it's a slight improvement over the previous arrangement already, especially since it includes an extra buttons and more indicators than in the past.
- Reset button for the frame counter. It can be found in the indicator toggle menu.
- Flag to toggle ember status. Since the game does not like it when you disable the ember status, your max HP will not go down, so keep that in mind. This appears to be a game issue in general.
- Indicator for the currently playing animation, as well as its time and max duration. The pointers for this and the ember status were taken from the TGA CT.

### CODE REVIEW

**Comment by Vinjul1704** [comment]
> Looks like the animation indicator might be broken on 1.12 and possibly other versions. I'll try to get that fixed later today or tomorrow.

Apparently it's the second offset that's the issue. `0x1F90`, needs to be `0x1F70` for 1.04 and `0x1F80` for 1.06 and 1.08 at least. I can't check all the versions myself currently, unfortunately.

**Comment by Vinjul1704** [comment]
> > Looks like the animation indicator might be broken on 1.12 and possibly other versions. I'll try to get that fixed later today or tomorrow.
> 
> Apparently it's the second offset that's the issue. `0x1F90`, needs to be `0x1F70` for 1.04 and `0x1F80` for 1.06 and 1.08 at least. I can't check all the versions myself currently, unfortunately, but I would assume it'll have to be`0x1F80` up until at least 1.12.

It is indeed `0x1F80` for 1.12.

**Comment by Vinjul1704** [comment]
Fixed the anim indicators for older versions. Tested on:
- v1.01, reg1.01
- v1.03, reg1.03
- v1.04, reg1.05
- v1.05, reg1.08
- v1.06, reg1.10
- v1.08, reg1.20
- v1.13, reg1.13
- v1.15, reg1.35

1.12 with offset `0x1F80` was tested before via CE.

**Review by veeenu — APPROVED** [review]
LGTM, thank you Vir :raised_hands:

**Pull request merged**
